# Generated by Django 4.0.3 on 2022-04-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grocery',
            name='date_published',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
