# Generated by Django 4.0.3 on 2022-04-02 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0004_remove_grocery_date_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.IntegerField(blank=True),
        ),
    ]
