# Generated by Django 4.0.3 on 2022-04-07 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShopItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('purchased', models.BooleanField(null=True)),
                ('shop_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shoplist_app.shoplist')),
            ],
            options={
                'ordering': ['-purchased'],
            },
        ),
    ]
