# Generated by Django 4.0.3 on 2022-04-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list_app', '0006_alter_grocery_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grocery',
            name='user',
        ),
        migrations.AlterField(
            model_name='grocery',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
