# Generated by Django 3.2.12 on 2022-04-12 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('messages_app', '0002_alter_tweet_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('tweet_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='messages_app.tweet')),
                ('tweet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='messages_app.tweet')),
            ],
            bases=('messages_app.tweet',),
        ),
    ]
