# Generated by Django 4.0.3 on 2022-04-09 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtask',
            name='priority',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3')], default=0),
        ),
        migrations.AlterField(
            model_name='priority',
            name='importance',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], default='Low', max_length=6),
        ),
    ]
