# Generated by Django 4.0.3 on 2022-04-08 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtask',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
