# Generated by Django 4.0.3 on 2022-04-09 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_newtask_priority_alter_priority_importance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Priority',
        ),
    ]
