# Generated by Django 4.0.3 on 2022-04-08 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_newtask_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtask',
            name='value',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
