# Generated by Django 4.0.3 on 2022-04-10 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_delete_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newtask',
            name='priority',
            field=models.IntegerField(blank=True, choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=1),
        ),
    ]
