# Generated by Django 4.0.3 on 2022-04-08 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='important',
            field=models.CharField(max_length=10),
        ),
    ]
