# Generated by Django 4.0.3 on 2022-04-09 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0005_alter_priority_important'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtask',
            name='value',
        ),
        migrations.AddField(
            model_name='priority',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
