# Generated by Django 4.0.3 on 2022-04-09 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0007_taggeditem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='important',
        ),
        migrations.AddField(
            model_name='priority',
            name='importance',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='Low', max_length=6),
        ),
    ]
