# Generated by Django 4.0.3 on 2022-04-09 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('todo_app', '0008_remove_priority_important_priority_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='newtask',
            name='content_type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='newtask',
            name='object_id',
            field=models.PositiveIntegerField(default=False),
        ),
        migrations.DeleteModel(
            name='TaggedItem',
        ),
    ]
