# Generated by Django 4.0.3 on 2022-04-09 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0011_newtask_content_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newtask',
            name='content_type',
        ),
    ]
