# Generated by Django 4.0.3 on 2022-04-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_priority_todo_delete_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='prioritychoice',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='priority',
            name='status',
            field=models.CharField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], max_length=10),
        ),
    ]
