# Generated by Django 4.0.3 on 2022-04-08 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_todoitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='name',
        ),
        migrations.AddField(
            model_name='priority',
            name='prior',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='low', max_length=100),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='todo_app.priority'),
        ),
    ]
