# Generated by Django 4.0.3 on 2022-04-09 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_remove_priority_name_priority_prior_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], on_delete=django.db.models.deletion.CASCADE, related_name='priority', to='todo_app.priority'),
        ),
    ]
