# Generated by Django 4.0.3 on 2022-04-09 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0004_alter_todoitem_priority'),
    ]

    operations = [
        migrations.AlterField(
            model_name='priority',
            name='prior',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='priority',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todoitems', to='todo_app.priority'),
        ),
    ]
