# Generated by Django 4.0.4 on 2022-04-18 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='text',
            new_name='groceryitem',
        ),
    ]
