# Generated by Django 4.0.3 on 2022-04-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0002_alter_priority_name_alter_todoitem_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='completed',
            field=models.DateTimeField(null=True),
        ),
    ]
