# Generated by Django 4.0.4 on 2022-05-18 22:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Occupation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Physician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='profile_img/PhysicianImg')),
                ('department', models.CharField(choices=[('Primary Care', 'Primary Care'), ('Billing', 'Billing'), ('Human Resources', 'Human Resources')], default='Primary Care', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.occupation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='profile_img/PatientImg')),
                ('date_seen', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField()),
                ('assessment', models.CharField(max_length=50)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CodeSpecialist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_img', models.ImageField(blank=True, null=True, upload_to='profile_img/CoderImg')),
                ('department', models.CharField(choices=[('Primary Care', 'Primary Care'), ('Billing', 'Billing'), ('Human Resources', 'Human Resources')], default='Billing', max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('occupation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_users.occupation')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
