# Generated by Django 4.0.4 on 2022-05-26 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='date_seen',
        ),
        migrations.AddField(
            model_name='patient',
            name='city',
            field=models.CharField(default='San Diego', max_length=30),
        ),
        migrations.AddField(
            model_name='patient',
            name='email',
            field=models.EmailField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='pt_address',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='state',
            field=models.CharField(default='CA', max_length=2),
        ),
        migrations.AddField(
            model_name='patient',
            name='zip_code',
            field=models.IntegerField(default='92109', max_length=6),
        ),
    ]
