# Generated by Django 4.0.4 on 2022-06-09 02:23

import api.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='historical_searches',
            field=api.models.SeparatedValuesField(default=[]),
            preserve_default=False,
        ),
    ]
