# Generated by Django 4.0.3 on 2022-04-09 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='priority',
            name='A',
        ),
        migrations.AddField(
            model_name='priority',
            name='list',
            field=models.CharField(choices=[('high', 'High'), ('medium', 'Meedium'), ('low', 'Low')], default='low', max_length=200),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
