# Generated by Django 4.0.1 on 2022-04-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('date_update', models.DateTimeField(auto_now_add=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(0, 'No'), (1, 'Yes')], default=0)),
            ],
            options={
                'ordering': ['-date_create'],
            },
        ),
    ]
