# Generated by Django 4.0.1 on 2022-04-09 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grocery',
            options={},
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='date_create',
            new_name='date_completed',
        ),
        migrations.RenameField(
            model_name='grocery',
            old_name='date_update',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='description',
        ),
        migrations.RemoveField(
            model_name='grocery',
            name='status',
        ),
        migrations.AddField(
            model_name='grocery',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='grocery',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
