# Generated by Django 3.2.12 on 2022-03-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chirpy_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Kiwi',
        ),
    ]
