# Generated by Django 4.0.3 on 2022-04-15 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0003_rename_created_date_todoitem_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='item',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
