# Generated by Django 4.0.3 on 2022-04-01 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groceryitem',
            old_name='list_item',
            new_name='items',
        ),
    ]
