# Generated by Django 4.0.3 on 2022-04-13 01:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('grocery_list', '0002_rename_list_item_groceryitem_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='items',
        ),
        migrations.RemoveField(
            model_name='groceryitem',
            name='user',
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='item',
            field=models.CharField(default=0, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groceryitem',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='grocery_list.department'),
        ),
    ]
