# Generated by Django 4.0.4 on 2022-05-11 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_groc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='item',
            name='date_completed',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
