# Generated by Django 4.0.4 on 2022-05-12 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_groc', '0003_alter_item_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='date_completed',
        ),
        migrations.AlterField(
            model_name='item',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='app_groc.storedepartment'),
        ),
    ]
